[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Optimizacion-Cristopher"
authors = [{name = "JCristopher", email = "cristopherruizbouchez@gmail.com"}]
dynamic = ["version", "description"]
